# Generated by Django 2.1.7 on 2019-05-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='Web', max_length=20),
        ),
    ]
