# Generated by Django 2.1.7 on 2019-05-29 07:46

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190529_1450'),
        ('news', '0005_auto_20190529_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', tinymce.models.HTMLField(max_length=100000)),
                ('contenthead', models.TextField(default='11', max_length=100000)),
                ('p_time', models.DateTimeField(auto_now_add=True)),
                ('biaoqian', models.CharField(default='无', max_length=128)),
                ('commend', models.BooleanField(default=False)),
                ('img', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='login.User')),
                ('fenlei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bainshu', to='news.Blog')),
            ],
            options={
                'verbose_name': '新闻',
                'ordering': ['p_time'],
                'verbose_name_plural': '新闻',
            },
        ),
    ]
