# Generated by Django 2.1.7 on 2019-06-03 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190603_0937'),
        ('news', '0009_news_bfenlei'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoucang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scnumber', to='news.News')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xihuan', to='login.User')),
            ],
            options={
                'verbose_name': '博客收藏',
                'verbose_name_plural': '博客收藏',
            },
        ),
    ]
