# Generated by Django 2.1.7 on 2019-06-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_shoucang'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='yuedushu',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
