# Generated by Django 2.1.7 on 2019-06-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_news_yuedushu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='yuedushu',
            field=models.IntegerField(default=0),
        ),
    ]
