# Generated by Django 2.1.7 on 2019-05-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='c_time',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='ch_time',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='status',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2019-05-18'),
        ),
    ]
