# Generated by Django 2.1.7 on 2019-06-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190529_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2019-06-03'),
        ),
    ]
