# Generated by Django 2.1.7 on 2019-05-16 06:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fenlei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '论坛小分支',
                'verbose_name_plural': '论坛小分支',
            },
        ),
        migrations.CreateModel(
            name='Luntan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '论坛类别',
                'verbose_name_plural': '论坛类别',
            },
        ),
        migrations.CreateModel(
            name='Pinglun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(max_length=21845)),
                ('p_time', models.DateTimeField(auto_now_add=True)),
                ('louceng', models.CharField(default=2, max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinglun', to='login.User')),
            ],
            options={
                'ordering': ['p_time'],
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luntan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guanzhushu', to='luntan.Luntan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guanzhu', to='login.User')),
            ],
            options={
                'verbose_name': '论坛关注关系',
                'verbose_name_plural': '论坛关注关系',
            },
        ),
        migrations.CreateModel(
            name='Tiezi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', tinymce.models.HTMLField(max_length=21845)),
                ('p_time', models.DateTimeField(auto_now_add=True)),
                ('fangwenshu', models.IntegerField(default=0)),
                ('top', models.BooleanField(default=False)),
                ('mostrecently', models.DateTimeField(default=datetime.datetime(2019, 5, 16, 14, 55, 52, 733754))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiezi', to='login.User')),
                ('luntan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luntan.Fenlei')),
            ],
            options={
                'ordering': ['p_time'],
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
            },
        ),
        migrations.AddField(
            model_name='pinglun',
            name='tiezi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pingluns', to='luntan.Tiezi'),
        ),
        migrations.AddField(
            model_name='fenlei',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fenlei', to='luntan.Luntan'),
        ),
    ]
