# Generated by Django 2.1.7 on 2019-05-16 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luntan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenlei',
            name='jingxuan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tiezi',
            name='mostrecently',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 15, 40, 20, 763416)),
        ),
    ]
