# Generated by Django 2.1.7 on 2019-05-18 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luntan', '0002_auto_20190516_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiezi',
            name='mostrecently',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 18, 50, 41, 991704)),
        ),
    ]
