# Generated by Django 2.1.7 on 2019-05-29 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luntan', '0004_auto_20190528_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiezi',
            name='mostrecently',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 14, 50, 4, 620774)),
        ),
    ]
