# Generated by Django 2.1.7 on 2019-06-03 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luntan', '0014_auto_20190529_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiezi',
            name='mostrecently',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 9, 37, 1, 369848)),
        ),
    ]
